Updated braille example for multiline headings
daisy/ebraille pull request #255
Opened 2024-08-22 16:01 UTC by wfree-aph

Made @bertfrees changes to the multiline heading example so it properly reflects how a balanced heading would appear in braille.

Also replaced br with wbr to match the changes made in PR #253

Fixes #229

[Preview](https://raw.githack.com/daisy/ebraille/update-styling-multiline-braille-example/best-practices/styling/index.html?developer-mode=true)

2024-08-23 08:37 UTC, bertfrees requested changes
It looks like the expected braille needs some further tweaking (proper centering). I can have a look at it.

2024-08-27 11:58 UTC, bertfrees commented on best-practices/styling/index.html
> +						example in [[tagging]] suggests using <code>wbr</code> elements to manually divide the
`br`should stay `br`.

2024-08-27 13:40 UTC, wfree-aph commented
@bertfrees Thanks for reviewing but your two comments have left me with questions. Why should `br` stay? And are you going to make the necessary changes or are you waiting for me to do so? I can close my PR if you would rather make these changes yourself.

2024-08-27 13:58 UTC, bertfrees commented
> Why should `br` stay?

I think the `wbr` change in [#253](https://github.com/daisy/ebraille/pull/253) is wrong. See my https://github.com/daisy/ebraille/pull/253#issuecomment-2306652137:

> `<wbr/>` is for creating line break opportunities in places where a line would otherwise not be broken. E.g. it is typically used inside words.

> are you going to make the necessary changes or are you waiting for me to do so?

Yes, I was planning to do that when I wrote it. But now I don't know whether I will have time. I was just going to check with the developer-mode feature whether the actual braille matches the expected. I suspect there is something wrong with the centering in the expected braille.

2024-08-27 17:40 UTC, wfree-aph commented
Thanks @bertfrees. I hadn't yet seen your other comment about `wbr`. I will make these changes today.

2024-08-29 13:46 UTC, wfree-aph commented
@bertfrees I think I have the changes needed in this latest commit. Please let me know what you think and thanks for looking it over.

2024-08-29 22:31 UTC, bertfrees commented
Looks good. I rebased onto main, and removed the references to issues #229 and #211.

2024-08-29 22:32 UTC, bertfrees approved these changes

2024-09-05 16:02 UTC, merged