Add sourceDate property
daisy/ebraille pull request #269
Opened 2024-09-23 13:39 UTC by mattgarrish

This pull request adds the property for expressing the date on which the source was published.

Should we also move this and sourcePublisher to the recommended properties list, as I asked in #221? Looking at the sourcePublisher definition, it says to add "N/A" if there isn't a source publisher, which is a strong case for not making it required.

Required metadata should always have a meaningful value, otherwise we keep having to propagate a workaround. It's never great to require language-specific values like "N/A", which I'll have to work into the date if we keep them required.

Fixes #200 

* [Preview](https://raw.githack.com/daisy/ebraille/spec/issue-200/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://daisy.github.io/ebraille/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/daisy/ebraille/spec/issue-200/index.html)

2024-09-23 15:10 UTC, clapierre requested changes
I am concerned about the prefix "a11y" as these are not accessibility metadata.
Is there something more appropriate?

2024-09-23 15:31 UTC, mattgarrish commented
The source publisher and source publication date are pretty unique to accessible format production and we're using a11y as a prefix for metadata that is broadly needed for accessible formats. I wouldn't try to read too much into a prefix.

We're also constrained by epub's reserved prefixes. If we mint something new, then the prefix has to be declared every time until we can convince the epub wg to adopt it as a reserved prefix (and then get the spec updated, and then get epubcheck updated...).

2024-09-26 13:24 UTC, mattgarrish commented
I've moved sourceDate and sourcePublisher to the recommended list. That they don't always apply is a strong case that they shouldn't be required to be present.

2024-09-30 13:42 UTC, mattgarrish commented
@clapierre I've tweaked the name of the vocabulary for this document to be more generic. That's probably the best we can do.

(I don't think we want to spilt hairs too finely about what constitutes accessibility metadata as don't forget we only created this space originally because the credential metadata in schema.org wasn't a perfect fit for what we needed.)

2024-10-01 16:12 UTC, merged